books:
  - name: deep work
    time: 20

blog:
  - deep work, part 1

convex_optimization:
  - name: week_avg
    time: 8
    repeat: 13

hertz:
  - name: hertz
    start: 8/15
    time: 40
    notes: "try to work on this during Michigan visit. finish as much as you can before semester begins"
    calendar: 1. urgent

facebook:
  # notes: "try to finish this before semester begins"
  - name: brain storm
    time: 8
    calendar: 1. urgent
  
  - name: first draft
    time: 8
    calendar: 1. urgent

  - name: iterating draft
    start: 9/2
    time: 20
    calendar: 1. urgent